authentication/urls.py
from django.urls import path,include
from . import views
app_name="auth"
urlpatterns=[
    path('', include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
    path('user/<int:pk>/',views.UserProfile.as_view(),name='userpage'),
    path('loggedout',views.userlogout,name='logout')
]

forum/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import  settings
from django.conf.urls.static import  static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('sections.urls')),
    path("",include('authentication.urls')),
    path('tinymce',include('tinymce.urls'))
]+staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sections/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('subforum/<int:pk>/createtopic/',views.CreateTopicView.as_view(),name='createtopic'),
    path("subforum/<int:pk>/",views.SubForumView.as_view(),name="subforum"),
    path("theme/<int:pk>/",views.TopicView.as_view(),name="topic"),
]

sections/models.py
from django.db import models
from tinymce.models import HTMLField
from django.conf import settings
# Create your models here.


class Forum(models.Model):
    name = models.CharField(max_length=30,default="Undefined Name")
    def __str__(self):
        return self.name


class SubForum(models.Model):
    section = models.ForeignKey(Forum,on_delete=models.CASCADE)
    name = models.CharField(max_length=30,default="Undefined Name")
    def total_messages(self):
        messages=0
        for topic in self.topic_set.all():
            messages+=topic.message_set.count()
        return messages
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=75)
    def get_topics(self):
        return Topic.objects.filter(tags__name=self.name)
    def __str__(self):
        return self.name
class Topic(models.Model):
    subforum = models.ForeignKey(SubForum,on_delete=models.CASCADE)
    theme = models.CharField(max_length=200)
    views = models.PositiveIntegerField(default=0,)
    time_created = models.DateTimeField(auto_now_add=True, blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag,blank=False)
    def __str__(self):
        return self.theme
    def getSubForum(self):
        return self.subforum


class Message(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,default='')
    text = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True, blank=True)
    def get_time_created(self):
        return self.time_created.strftime('%b. %d, %Y, %I:%M %p')
    def __str__(self):
        return self.text[:30]+'...'

sections/forms.py
from django import forms
from .models import Message,Topic,Tag
from tinymce.widgets import TinyMCE
from django.core.exceptions import ValidationError
class MessageForm(forms.Form):
    message = forms.CharField(label="",widget=TinyMCE())
class CreateTopicForm(forms.ModelForm):
    message =  forms.CharField(label="", required=True, widget=TinyMCE())
    tags = forms.CharField(required=True)
    class Meta:
        model = Topic
        fields =('theme',)

    def get_tags(self):
        return [Tag.objects.get(name=i) for i in self.cleaned_data['tags'].replace(' ', '').split(',')]

    def clean(self):
        cd = self.cleaned_data
        tags = cd['tags'].replace(' ', '').split(',')
        for tag in tags:
            if  not Tag.objects.filter(name=tag).exists():
                self.add_error('tags', "check your tags!")
                raise ValidationError("")
        return cd

sections/views.py
from django.views import generic,View
from django.http import JsonResponse
from django.shortcuts import get_object_or_404,render,reverse
from django.urls import reverse_lazy
from .models import Forum,SubForum,Topic,Message,Tag
from .forms import MessageForm, CreateTopicForm
from django.contrib.auth.mixins import LoginRequiredMixin
class IndexView(View):
    template_name = 'sections/index.html'
    context_object_name = 'forums'
    def get(self,request):
        return render(request,self.template_name, {'forums': Forum.objects.order_by('name'),
                                                   'last_topics': Topic.objects.order_by('-time_created')[:4]
                                                  })


class SubForumView(generic.DetailView):
    template_name = 'sections/subforum.html'
    context_object_name = 'subforum'
    model = SubForum


class TopicView(View):
    template_name = 'sections/topic.html'
    model = Topic
    form_class = MessageForm

    def get(self,request,**kwargs):
        topic = get_object_or_404(Topic,pk=kwargs['pk'])
        topic.views+=1
        topic.save()
        return render(request,self.template_name,{'topic':topic,'form':self.form_class})

    def post(self,request,**kwargs):
        print(request.POST)
        print(kwargs)
        message = request.POST.get('message', None)
        topic = Topic.objects.get(pk=kwargs['pk'])
        message = Message.objects.create(
            creator=request.user,
            topic=topic,
            text=message
        )
        message.save()
        data = {
            'creator': message.creator.username,
            'message': message.text,
            'time_created': message.time_created.strftime('%b. %d, %Y, %I:%M %p')
        }
        return JsonResponse(data)


class CreateTopicView(LoginRequiredMixin,generic.FormView):
    login_url = '/login/'
    template_name = 'sections/createanswer.html'
    form_class = CreateTopicForm

    def get(self,request,*args,**kwargs):
        return render(request,self.template_name,{
            'form': self.form_class,
            'tags': [tag.name for tag in Tag.objects.all()],
            'pk':kwargs['pk']
        })

    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            tags = form.get_tags()
            topic = Topic.objects.create(
                subforum=SubForum.objects.get(pk=kwargs['pk']),
                theme=form.cleaned_data['theme'],
                creator=request.user)
            for tag in tags:
                topic.tags.add(tag)
            message = Message.objects.create(
                creator=request.user,
                text=form.cleaned_data['message'],
                topic=topic,
            )
            topic.save()
            message.save()
            return JsonResponse({
                'redirect_url': reverse('topic',args=(topic.id,))
            })
        else:
            return JsonResponse({
                'errors_list':form.errors
            })

sections/templates/sections/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="/static/sections/css/index.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
{% block header %}
    {% include 'sections/menu.html' %}
{% endblock %}

{% block main-content %}
{% endblock %}


{% block javascript %}
{% endblock %}
</body>
</html>

sections/templates/sections/createanswer.html
{% extends 'sections/base.html' %}
{% block head %}
    <link rel="stylesheet" href="/static/sections/css/createanswer.css">
    {{ form.media }}
{% endblock %}
{% block main-content %}

<form action="{% url 'createtopic' pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
   <div class="suggestions">
    </div>
 <button type="submit" > Send</button>
</form>
{% else %}
    {% include 'sections/please_login.html' %}
{% endblock %}
{% block javascript %}
    <script>
        let tags = {{ tags | safe }};
        $('#id_tags').on('input',function(){
            $('.suggestions').html('');
            let text = $(this).val();
            let inputTags = text.replace(/ /g,'').split(',');
            let lastTag = inputTags[inputTags.length - 1];
            if(lastTag!="") {
                for (let tagIndex in tags) {
                    if (tags[tagIndex].indexOf(lastTag) != -1) {
                        console.log(tags[tagIndex])
                        $('.suggestions').append(`<p>${tags[tagIndex]}</p>`)
                        $('.suggestions p').on('click',function(){
                            inputTags[inputTags.length - 1] = this.innerHTML;
                            $('#id_tags').val(inputTags.toString())
                        });
                    }
                }
            }
        });
        $('form').on('submit',function (e) {
           $.ajax({
                data:$(this).serialize(),
                type:$(this).attr('method'),
                url:$(this).attr('action'),
                success:function (data) {
                    console.log(data);
                    if(data.errors_list) {
                        Object.keys(data.errors_list).forEach(function (key) {
                            $('#id_'+key).after('');
                            $('#id_'+key).after(` <p class='error'>${data.errors_list[key][0]}</p>`)
                        });
                        $('form').append(data.errors_list)
                    }
                    else if(data.redirect_url) window.location.href=data.redirect_url
                }
           });
         return false // to prevent form redirect
        });
        function show_error(message) {
            $('.errors').append(`<p>${message}</p>`);
        }
    </script>
{% endblock %}

sections/templates/sections/index.html
{% extends  'sections/base.html' %}
{% block header %}
<div class="welcome">
{% include 'sections/menu.html' %}
<p>WELCOME TO FORUM</p>
</div>
{% endblock %}
{% block main-content %}
{% if forums %}
    <div class="content main">
        <div class="forums radius">
            {% for forum in forums %}
                <div class="forum radius">
                <div class="name forumname">
                    <p>{{ forum }}</p>
                </div>
                    <div class="table border">
                        <div class="row_info">Forum</div>
                        <div class="row_info">Topics</div>
                        <div class="row_info">Messages</div>
                        {% for subforum in forum.subforum_set.all %}
                            <div class="subforum_info"><a href="/subforum/{{ subforum.id }}">{{ subforum }}</a></div>
                            <div class="subforum_info">{{ subforum.topic_set.count }}</div>
                            <div class="subforum_info"> {{ subforum.total_messages }} </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="last_themes radius">
            <div class="name asideblock"><p>NEW FORUM POSTS</p></div>
           {% for topic in last_topics %}
            <div class="lastpost border">
                   <p class="last_post_name"><a href="{% url 'topic' topic.id %}"> {{ topic.theme }} </a></p>
                    <p>by <span>{{ topic.creator }}</span></p>
                    <p> {{ topic.time_created }}</p>
            </div>
           {% endfor %}
        </div>
    </div>
    {% else %}
    <p>No forums :(</p>
{% endif %}
{% endblock %}

sections/templates/sections/last_themes.html
<div class="last_themes radius">
            <div class="name asideblock"><p>NEW FORUM POSTS</p></div>
           {% for topic in last_topics %}
            <div class="lastpost border">
                   <p class="last_post_name"><a href="{% url 'topic' topic.id %}"> {{ topic.theme }} </a></p>
                    <p>by <span>{{ topic.creator }}</span></p>
                    <p> {{ topic.time_created }}</p>
            </div>
           {% endfor %}
        </div>

sections/templates/sections/menu.html
    <div class="menu">
    <span><a href="{% url 'index' %}">Home</a></span>
    <ul>
        <li>FAQ</li>
         {% if user.is_authenticated %}
           <li> <a href="{% url 'auth:userpage' user.id %}">{{ user }}</a></li>
           <li>
                <a href="{% url 'auth:logout' %}">Exit</a>
           </li>
        {% else %}
             <li><a href="{% url 'auth:login' %}">Login</a> or <a href="{% url 'auth:register' %}">Register</a></li>


        {% endif %}
    </ul>
</div>

sections/templates/sections/please_login.html
<p>Please <li><a href="{% url 'auth:login' %}">Login</a> or <a href="{% url 'auth:register' %}">Register</a></li></p>

sections/templates/sections/subforum.html
{% extends 'sections/base.html' %}

{% block main-content %}
<div class="info">
<p><a href="{% url 'index' %}"/>Forum</a> > {{ subforum }}</p>
{% if user.is_authenticated  %}
<p><a href="{% url 'createtopic' subforum.id %}">Create Answer</a></p>
{% endif %}

</div>

<div class="main">
{% ifnotequal subforum.topic_set.all.count  0 %}
    <div class="table border">
        <div class="row_info">Theme</div>
        <div class="row_info">Views</div>
        <div class="row_info">Messages</div>
        {% for topic in subforum.topic_set.all|dictsortreversed:"time_created" %}
            <div class="subforum_info"><a href="{% url 'topic' topic.id %}">{{ topic }}</a></div>
            <div class="subforum_info">{{ topic.views }}</div>
            <div class="subforum_info">{{ topic.message_set.count }}</div>
        {% endfor %}
    </div>
{% else %}
<p>No Topics :(</p>
{% endifnotequal %}
</div>
{% endblock %}

sections/templates/sections/topic.html
{% extends 'sections/base.html' %}
{% block head %}
    <link rel="stylesheet" href="/static/sections/css/topic.css" type="text/css">
    <link rel="stylesheet" href="/static/sections/css/prism.css" type="text/css">
    <script src="/static/sections/js/prism.js"></script>
    {{ form.media }}
{% endblock %}
{% block main-content %}

    <div class="main">
        <div class="messages">
        {% ifnotequal topic.message_set.all.count 0 %}
            {% for message  in topic.message_set.all %}
                <div class="message">
                    <p class="creator"><b>{{ message.creator }}</b> <span class="date">{{ message.get_time_created }}</span></p>
                    <div class="message_text">{{ message.text|safe  }}</div>
                </div>
            {% endfor %}
        {% else %}
        <p>No messages</p>
        {% endifnotequal %}
        </div>
        <p><b>Your Answer</b></p>
        <hr>
    {% if user.is_authenticated %}
     <form  method="post" action="{% url 'topic' topic.id %}" id="form">
            {% csrf_token %}
            {{ form }}
            <button type="submit"  id="submit">Submit</button>
        </form>
        {% block javascript %}
    <script>
        $('#form').submit(function () {
            $.ajax({ // create an AJAX call...
                data:$(this).serialize() , // get the form data
                type: $(this).attr('method'), // GET or POST
                url: $(this).attr('action'), // the file to call
                success: function(response) { // on success..
                    console.log(response)
                    $('.messages').append(`
                    <div class="message">
                        <p class="creator"><b>${ response.creator }</b> <span class="date">${ response.time_created}</span></p>
                        <p class="message_text">${ response.message }</p>
                    </div>`
                    )
                    tinyMCE.activeEditor.setContent('')
                    Prism.highlightAll()
                }
            });
            return false;
        });
    </script>
{% endblock %}
     {% else %}
         {% include 'sections/please_login.html' %}
    {% endif %}

    </div>

{% endblock %}